// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptcefzqzsflmybhhpen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGNlZnpxenNmbG15YmhocGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjMzNDksImV4cCI6MjA2NzQzOTM0OX0.K7NL_Pusn3fH6Qv7qPkoIwfz1hJy8fqV3BPbYHDvHTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});